name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.0'

    - name: Build
      run: hugo --minify

    - name: Deploy
      run: aws s3 sync public/ s3://${{ secrets.S3_PATH }} --storage-class ONEZONE_IA
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
